export default function Spreadsheet() {
    return <table>
        <thead>
            <tr>
                <th></th>
                <th>A</th>
                <th>B</th>
                <th>C</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>2</td>
                <td></td>
                <td>5</td>
                <td></td>
            </tr>
            <tr>
                <td>3</td>
                <td></td>
                <td>2.1</td>
                <td>3.4</td>
            </tr>
        </tbody>
    </table>;
}